### ISSUE TITLE
Install monotonic_align

### ISSUE THREAD

**Issue by andri-jpg** [HRNPH/AIwaifu#32]
When i use new environment, i got error like this, i think we need to add some command in readme to install some extra dependency after you add sovits folder

PS D:\AIwaifu> & D:/miniconda3/python.exe d:/AIwaifu/main.py
Initializing... Dependencies
Traceback (most recent call last):
  File "d:\AIwaifu\main.py", line 19, in <module>
    from AIVoifu.voice_conversion import vc_inference as vc
  File "d:\AIwaifu\AIVoifu\voice_conversion\vc_inference.py", line 13, in <module>
    from .Sovits.data_utils import UnitAudioLoader, UnitAudioCollate
  File "d:\AIwaifu\AIVoifu\voice_conversion\Sovits\data_utils.py", line 10, in <module>
    from .models import SynthesizerTrn
  File "d:\AIwaifu\AIVoifu\voice_conversion\Sovits\models.py", line 10, in <module>
    from . import monotonic_align
  File "d:\AIwaifu\AIVoifu\voice_conversion\Sovits\monotonic_align\__init__.py", line 3, in <module>
    from .monotonic_align.core import maximum_path_c
ModuleNotFoundError: No module named 'AIVoifu.voice_conversion.Sovits.monotonic_align.monotonic_align'

**Comment by Sylensar** [comment]
Collecting pyopenjtalk
  Using cached pyopenjtalk-0.3.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      Traceback (most recent call last):
        File "C:\Users\Young\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Young\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Young\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Young\AppData\Local\Temp\pip-build-env-g3lwgpso\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\Young\AppData\Local\Temp\pip-build-env-g3lwgpso\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\Young\AppData\Local\Temp\pip-build-env-g3lwgpso\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Young\AppData\Local\Temp\pip-build-env-g3lwgpso\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 153, in <module>
        File "C:\Users\Young\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\Young\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\Young\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by HRNPH** [comment]
> Collecting pyopenjtalk
>   Using cached pyopenjtalk-0.3.0.tar.gz (1.5 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [25 lines of output]
>       setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
>         _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
>       Traceback (most recent call last):
>         File "C:\Users\Young\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>           main()
>         File "C:\Users\Young\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "C:\Users\Young\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>         File "C:\Users\Young\AppData\Local\Temp\pip-build-env-g3lwgpso\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
>           return self._get_build_requires(
>         File "C:\Users\Young\AppData\Local\Temp\pip-build-env-g3lwgpso\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
>           self.run_setup()
>         File "C:\Users\Young\AppData\Local\Temp\pip-build-env-g3lwgpso\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
>           super(_BuildMetaLegacyBackend,
>         File "C:\Users\Young\AppData\Local\Temp\pip-build-env-g3lwgpso\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
>           exec(compile(code, __file__, 'exec'), locals())
>         File "setup.py", line 153, in <module>
>         File "C:\Users\Young\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
>           with Popen(*popenargs, **kwargs) as process:
>         File "C:\Users\Young\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
>           self._execute_child(args, executable, preexec_fn, close_fds,
>         File "C:\Users\Young\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
>           hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>       FileNotFoundError: [WinError 2] The system cannot find the file specified
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> 

wrong thread!
look at #20
