### ISSUE TITLE
Error installing pyopenjtalk

### ISSUE THREAD

**Issue by Zinedinarnaut** [HRNPH/AIwaifu#48]
I keep getting this error and I don't know how to resolve it I've tried all the steps above but it keeps outputting this error when installing pyopenjtalk

  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      Traceback (most recent call last):
        File "C:\Users\PycharmProjects\AIwaifu\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\PycharmProjects\AIwaifu\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\PycharmProjects\AIwaifu\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\AppData\Local\Temp\pip-build-env-xn3bmdr3\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\AppData\Local\Temp\pip-build-env-xn3bmdr3\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\AppData\Local\Temp\pip-build-env-xn3bmdr3\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\AppData\Local\Temp\pip-build-env-xn3bmdr3\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 153, in <module>
        File "C:\Users\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by andri-jpg** [comment]
What version of python are you using?

**Comment by HRNPH** [comment]
please try using python 3.8.x

**Comment by Zinedinarnaut** [comment]
> What version of python are you using?

Python: 3.10

**Comment by HRNPH** [comment]
man we really need to migrate to poetry for dependencies management

**Comment by Zinedinarnaut** [comment]
Thank you for your help everything is working successfully, any plans on making a discord server for this? would help a lot of newcomers.

**Comment by HRNPH** [comment]
Thx @Zinedinarnaut for Good Suggestion, I'll do it

**Comment by Zinedinarnaut** [comment]
Understood, I’ll clarify what fixed the error for next time.

**Comment by HRNPH** [comment]
oh yeah, Thx I've updated it
