### ISSUE TITLE
Doesn't detect/use gpu

### ISSUE THREAD

**Issue by Jake36921** [HRNPH/AIwaifu#50]
everything works fine except its using my cpu instead of the gpu.
![image](https://github.com/HRNPH/AIwaifu/assets/113159896/6e6c0c61-3425-47f6-8ad8-c75721eed7bc)
![image](https://github.com/HRNPH/AIwaifu/assets/113159896/a905e50b-c70a-4edf-b712-add0934c8e48)
![image](https://github.com/HRNPH/AIwaifu/assets/113159896/afc70447-88d1-4b2f-82fd-19dc4317f930)

**Comment by Jake36921** [comment]
Cuda seems to be installed from what I've read
![image](https://github.com/HRNPH/AIwaifu/assets/113159896/76f80e37-c6db-4756-90ce-4e80c4ab0ed4)
![image](https://github.com/HRNPH/AIwaifu/assets/113159896/0f33a6f6-a955-44fe-9285-66b7f04439be)

**Comment by HRNPH** [comment]
This Is Legit that you have driver, but please check if your driver is the correct version?
https://stackoverflow.com/questions/60987997/why-torch-cuda-is-available-returns-false-even-after-installing-pytorch-with

**Comment by Jake36921** [comment]
The newest Nvidia drivers (536.67) probably messed up something. I'll try to see if rolling back the drivers would fix it.

**Comment by Jake36921** [comment]
It still doesn't detect the gpu after rolling back to previous drivers and installing pytorch with cuda 11.8

**Comment by HRNPH** [comment]
this maybe a little bit troblesome
can you try activate your environment
and type the fllowing?

```bash
python
```

```python
import torch
print(torch.cuda.is_available())
```
if it's return true?
I need to know if it's a problem with Torch

**Comment by HRNPH** [comment]
this maybe a little bit troblesome
can you try activate your environment
and type the following?

```bash
python
```

```python
import torch
print(torch.cuda.is_available())
```
if it's return true?
I need to know if it's a problem with Torch
if it's return true then it's my code that's a problem

**Comment by Jake36921** [comment]
(venv) PS E:\etc\AIwaifu> python
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.is_available())
False

**Comment by HRNPH** [comment]
try using poetry installation method provided in the readme instead

**Comment by Jake36921** [comment]
Most of the file installations worked fine but pyopenjtalk caused errors

(E:\etc\AIwaifu\envs) PS E:\etc\AIwaifu> poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing pyopenjtalk (0.3.0)

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  Traceback (most recent call last):
    File "E:\etc\AIwaifu\envs\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "E:\etc\AIwaifu\envs\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "E:\etc\AIwaifu\envs\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\rapha\AppData\Local\Temp\tmpwvp73fs9\.venv\lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\rapha\AppData\Local\Temp\tmpwvp73fs9\.venv\lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "C:\Users\rapha\AppData\Local\Temp\tmpwvp73fs9\.venv\lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\rapha\AppData\Local\Temp\tmpwvp73fs9\.venv\lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 153, in <module>
    File "E:\etc\AIwaifu\envs\lib\subprocess.py", line 493, in run
      with Popen(*popenargs, **kwargs) as process:
    File "E:\etc\AIwaifu\envs\lib\subprocess.py", line 858, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "E:\etc\AIwaifu\envs\lib\subprocess.py", line 1327, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified


  at envs\lib\site-packages\poetry\installation\chef.py:147 in _prepare
      143│
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│
      146│             if error is not None:
    → 147│                 raise error from None
      148│
      149│             return path
      150│
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pyopenjtalk (0.3.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pyopenjtalk (==0.3.0)"'.

(E:\etc\AIwaifu\envs) PS E:\etc\AIwaifu>

**Comment by HRNPH** [comment]
try 
```bash
poetry run pip install --no-use-pep517 pyopenjtalk==0.3.0
```

**Comment by Jake36921** [comment]
Doesn't work either
(E:\etc\AIwaifu\envs) PS E:\etc\AIwaifu> poetry run pip install --no-use-pep517 pyopenjtalk==0.3.0
Collecting pyopenjtalk==0.3.0
  Using cached pyopenjtalk-0.3.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      C:\Users\rapha\AppData\Local\Temp\pip-install-znxh0qf3\pyopenjtalk_1b86cc28ee3946f4a72d6ca7a097986c\setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\rapha\AppData\Local\Temp\pip-install-znxh0qf3\pyopenjtalk_1b86cc28ee3946f4a72d6ca7a097986c\setup.py", line 153, in <module>
          r = run(["cmake", "..", "-DHTS_ENGINE_INCLUDE_DIR=.", "-DHTS_ENGINE_LIB=dummy"])
        File "E:\etc\AIwaifu\envs\lib\subprocess.py", line 493, in run
          with Popen(*popenargs, **kwargs) as process:
        File "E:\etc\AIwaifu\envs\lib\subprocess.py", line 858, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "E:\etc\AIwaifu\envs\lib\subprocess.py", line 1327, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by HRNPH** [comment]
I'll try to solve this at my end, please bear it until next released

**Comment by HRNPH** [comment]
> I have this gpu and I'll take a look and see if I can reproduce this issue

Thx! please notify me in Discord if you saw what's the problem and don't have enough time to fix it!

**Comment by HRNPH** [comment]
I've got my 4080 16GB delivered now
I'll begin reproducing it
